app/models/colleges.py
from app.views import colleges
from .. import db, mycursor


class Colleges():
    def __init__(self, code = None, name = None):

        self.code = code
        self.name = name
    
    def get_all(self):
        query = 'SELECT * FROM colleges'
        mycursor.execute(query)
        result = mycursor.fetchall()
        colleges = [list(colleges) for colleges in result]
        return colleges 

    def get_one(self,id):
        query = 'SELECT * FROM colleges WHERE code=%s'
        mycursor.execute(query,(id,))
        result = mycursor.fetchone()
        #students = [list(student) for student in result]
        return result 
    
    def search(self, q=None):
        query = 'SELECT * FROM colleges WHERE concat(code, name) LIKE %s'
        mycursor.execute(query, ('%' + q + '%',))
        result = mycursor.fetchall()
        colleges = [list(colleges) for colleges in result]
        return colleges

app/views/colleges/__init__.py
from flask import Blueprint

college = Blueprint('college', __name__)

from . import routes

app/views/colleges/routes.py
from flask import Flask, render_template, request, redirect, url_for, flash
from ...models.colleges import Colleges
from . import college
from ... import db,mycursor

@college.route('/colleges')
def colleges():


    data = Colleges().get_all()
    return render_template('/colleges/index.html', colleges=data )

@college.route('/delete/<string:code>', methods = ['GET'])
def delete(code):
    flash("Deleted Successfully")
    mycursor.execute("DELETE FROM colleges WHERE code=%s", (code,))
    db.commit()
    return redirect(url_for('college.colleges')) 


@college.route('/insert', methods = ['POST', 'GET'])
def insert():

    if request.method == "POST":
        flash("Data Saved Successfully")
        code = request.form['code']
        name = request.form['name']
      
        mycursor.execute("INSERT INTO colleges (code, name) VALUES (%s,%s)", (code, name))
        db.commit()
        return redirect(url_for('college.colleges'))
    return render_template('/colleges/add.html')



@college.route('/update/<string:code>',methods=['POST','GET']) 
def update(code):

    if request.method == 'POST':
        newcode = request.form['code']
        name = request.form['name']
        mycursor.execute("""
               UPDATE colleges
               SET code=%s, name=%s 
               WHERE code=%s
            """,(newcode, name, code))
        flash("Data Updated Successfully")
        db.commit()
        return redirect(url_for('college.colleges'))
    data = Colleges().get_one(code)
    return render_template('/edit/college2.html',code=code, data=data)

@college.route('/search')
def search():
    q = request.args.get('q') or None
    data = Colleges().search(q)
    return render_template('/colleges/index.html', colleges=data )




# step 1. Create blueprint (views>colleges>__init__.py)
# step 2. Register blueprint (app>__init__.py)
# step 3. Use blueprint to define the routes (views>colleges>routes.py)
# step 4. Create models (models>colleges.py)

app/templates/colleges/add.html
{% extends "base.html" %}
{% block title %} Create College{% endblock %}
{% block content %}
<h1> Simple Student Information System </h1>
<section class="create-type">
	<div class="container">
		<h2>CREATE COLLEGE HERE</h2>
		{% with messages = get_flashed_messages() %}
			{% if messages %}
				{% for msg in messages %}
					<p class="text-center">{{msg}}</p>
				{% endfor %}
			{% endif %}
		{% endwith %}
		<form action="" method="POST" class="form-group">
			<label for="college-code" class="form-label">College code</label>
			<input type="text" class="form-control" id="code" name="code" placeholder="e.g CCS">
			<label for="college-name" class="form-label">College name</label>
			<input type="text" class="form-control" id="name" name="name" placeholder="e.g College of Computer Studies">
			<input type="submit" name="submit-college" class="btn btn-primary form-control" value="Create">
			<a href="{{ url_for('college.colleges' ) }}" class="btn btn-info form-control">Back</a>
		</form>
	</div>
</section>
{% endblock %}

app/templates/colleges/index.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="../static/style.css">

    <title>SSIS</title>
  </head>



  <body>

    <!-- Navigation bar-->
    <nav class="navbar container">
      <div class="nav-item pull-left">
      <ul class="nav">
          
          <a class="navbar-brand" href="/">
            <img src="{{url_for('static',filename='logo.png')}}" width="30" height="30" class="d-inline-block align-top" alt="" loading="lazy">
          </a>
          
          <li class="nav-item p-2" style="font-size:20px">
              <a href="{{url_for('student.students')}}" style="color:#850f13"><strong><u>Student List</u></strong></a>
          </li>
          <li class="nav-item p-2" style="font-size:20px">
              <a href="{{url_for('course.courses')}}" style="color:#850f13"><strong>Course List</strong></a>
          </li>
         
          
          <li class="nav-item p-2" style="font-size:20px">
              <a href="{{url_for('college.colleges')}}" style="color:#ff5733"><strong>College List</strong></a>
          </li>
      </ul>
      </div>
      <form action="{{url_for('college.search')}}" method="GET" class="form-inline my-2 my-lg-0 d-flex">
          <input class="form-control mr-sm-2" type="text" name="q" id="searchInput" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
  </nav>
    <!-- End of navigation bar-->
    
    
    
    <div class="container">

      <div class="row">
  
          <div class="col md-12">

            <p align="right">
  
              <a  class="btn btn-success  pull-left" href="{{ url_for('.insert' ) }}">Add College</a>
          </p>
    
  
    
    </form>

    <!-- Table -->
    <table class="table container">
        <thead>
          <tr>
            <th scope="col">Code</th>
            <th scope="col">Name</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
            {% for college in colleges %}
            <tr>
                <th>{{college.0}}</th>
                <th>{{college.1}} </th>
                <th>
                  <a  class="btn btn-primary" href="{{ url_for('.update', code=college.0) }}">Update</a>
                  <a class="btn btn-danger" href="{{ url_for('.delete', code=college.0) }}">Delete</a>
                </th>
            </tr>
            {% endfor %}
        </tbody>
      </table>
    <!-- End of Table-->



  </body>
</html>