app/models/students.py
from app.views import students
from .. import db, mycursor



class Student():
    def __init__(self, 
        id= None, 
        firstname = None,  
        lastname = None, 
        yearlevel = None, 
        gender = None, 
        coursecode = None):
        
    
        self.id = id
        self.firstname = firstname
        self.lastname = lastname
        self.yearlevel = yearlevel
        self.gender = gender
        self.coursecode = coursecode


    def get_all(self):
        query = 'SELECT * FROM students'
        mycursor.execute(query)
        result = mycursor.fetchall()
        students = [list(student) for student in result]
        print (students)

        return students

    def get_one(self,id):
        query = 'SELECT * FROM students WHERE id=%s'
        mycursor.execute(query,(id,))
        result = mycursor.fetchone()
        #students = [list(student) for student in result]
        return result

    def search(self, q=None):
        #query = 'SELECT * FROM students WHERE concat(id, firstname, lastname, gender, coursecode, yearlevel) LIKE %s'
        query = 'SELECT * FROM students WHERE concat(id, firstname, lastname, gender, COALESCE(coursecode,""), yearlevel) LIKE %s'
        mycursor.execute(query, ('%' + q + '%',))
        result = mycursor.fetchall()
        students = [list(student) for student in result]
        return students

app/views/students/__init__.py
from flask import Blueprint

student = Blueprint('student', __name__)

from . import routes

app/views/students/routes.py
from flask import Flask, render_template, request, redirect, url_for, flash
from ...models.students import Student
from . import student
from ... import db,mycursor
from cloudinary.uploader import upload as cloudinary_upload, destroy as cloudinary_destroy
from cloudinary.utils import cloudinary_url

@student.route('/students') 
def students():
    data = Student().get_all()
    return render_template('/students/index.html', students=data, cloudinary_url=cloudinary_url)


@student.route('/delete/<string:id_number>', methods = ['GET'])
def delete(id_number):
    flash("Student Record Has Been Deleted Successfully")
    mycursor.execute("DELETE FROM students WHERE id=%s", (id_number,))
    db.commit()
    return redirect(url_for('student.students')) 


@student.route('/insert', methods = ['POST', 'GET'])
def insert():

    if request.method == "POST":
        flash("Data Saved Successfully")
        id_number = request.form['id_number']
        firstname = request.form['firstname']
        lastname = request.form['lastname']
        gender = request.form['gender']
        coursecode = request.form['coursecode']
        yearlevel = request.form['yearlevel']
        photo = request.files['photo']
        if photo:
            cloudinary_response = cloudinary_upload(photo, upload_preset='ml_default', invalidate=True)
            new_photo = cloudinary_response['public_id']
        else:
            new_photo=""
        mycursor.execute("INSERT INTO students (id, firstname, lastname, gender, coursecode, yearlevel, photo) VALUES (%s,%s, %s, %s, %s, %s, %s)", (id_number,firstname, lastname, gender, coursecode, yearlevel, new_photo))
        db.commit()
        return redirect(url_for('student.students'))
    return render_template('/students/add.html')



@student.route('/update/<string:id_number>',methods=['POST','GET']) 
def update(id_number):

    if request.method == 'POST':
        newid_number = request.form['id_number']
        firstname = request.form['firstname']
        lastname = request.form['lastname']
        gender = request.form['gender']
        coursecode = request.form['coursecode']
        yearlevel = request.form['yearlevel']
        photo = request.files['photo']
        if photo:
            cloudinary_response = cloudinary_upload(photo, upload_preset='ml_default', invalidate=True)
            new_photo = cloudinary_response['public_id']
            mycursor.execute("""
                UPDATE students
                SET id=%s, firstname=%s, lastname=%s, gender=%s, coursecode=%s, yearlevel=%s, photo=%s
                WHERE id=%s
                """, (newid_number, firstname, lastname, gender, coursecode, yearlevel, new_photo, id_number))
        else:
           
            mycursor.execute("""
                UPDATE students
                SET id=%s, firstname=%s, lastname=%s, gender=%s, coursecode=%s, yearlevel=%s
                WHERE id=%s
                """, (newid_number, firstname, lastname, gender, coursecode, yearlevel, id_number))
        flash("Data Updated Successfully")
        db.commit()
        return redirect(url_for('student.students'))
    data = Student().get_one(id_number)
    return render_template('/edit/student2.html',id_number=id_number, data=data)

@student.route('/search')
def search():
    q = request.args.get('q') or None
    data = Student().search(q)
    return render_template('/students/index.html', students=data, cloudinary_url=cloudinary_url )

app/templates/students/add.html
{% extends "base.html" %}
{% block title %} Create Student{% endblock %}
{% block content %}
<h1> Simple Student Information System </h1>
<section class="create-type">
	<div class="container">
		<h2>CREATE STUDENT HERE</h2>
		{% with messages = get_flashed_messages() %}
			{% if messages %}
				{% for msg in messages %}
					<p class="text-center">{{msg}}</p>
				{% endfor %}
			{% endif %}
		{% endwith %}
		<form action="" method="POST" class="form-group" enctype="multipart/form-data">
			<label for="id_number">ID Number: </label>
			<input type="text" name="id_number" id="id_number" class="form-control" placeholder="2022-0000" value={{id_number}}>

			<label for="firstname">First Name: </label>
			<input type="text" name="firstname" id="firstname" class="form-control" placeholder="Cyrus">

			<label for="lastname">Last Name:</label>
			<input type="text" name="lastname" id="lastname" class="form-control" placeholder="Conde">

			<label for="gender">Gender: </label>
			<input type="text" name="gender" id="gender" class="form-control" placeholder="MALE">

			<label for="coursecode">Course: </label>
			<input type="text" name="coursecode" id="coursecode" class="form-control" placeholder="BSIT">

			<label for="yearlevel">Year Level: </label>
			<input type="text" name="yearlevel" id="yearlevel" class="form-control" placeholder="3">

			<input type="file" name="photo">

			<input type="submit" name="create-student" id="create-student" class="btn btn-primary form-control" value="CREATE">
			<a href="{{ url_for('student.students' ) }}" class="btn btn-info form-control">Back</a>
		</form>
	</div>
</section>
{% endblock %}

app/templates/students/index.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="../static/style.css">

    <title>SSIS</title>
  </head>



  <body>

    <!-- Navigation bar-->
    <nav class="navbar container">
      <div class="nav-item pull-left">
      <ul class="nav">
          
          <a class="navbar-brand" href="/">
            <img src="{{url_for('static',filename='logo.png')}}" width="30" height="30" class="d-inline-block align-top" alt="" loading="lazy">
          </a>
          
          <li class="nav-item p-2" style="font-size:20px">
              <a href="{{url_for('student.students')}}" style="color:#ff5733"><strong><u>Student List</u></strong></a>
          </li>
          <li class="nav-item p-2" style="font-size:20px">
              <a href="{{url_for('course.courses')}}" style="color:#850f13"><strong>Course List</strong></a>
          </li>
         
          
          <li class="nav-item p-2" style="font-size:20px">
              <a href="{{url_for('college.colleges')}}" style="color:#850f13"><strong>College List</strong></a>
          </li>
      </ul>
      </div>
      <form action="{{url_for('student.search')}}" method="GET" class="form-inline my-2 my-lg-0 d-flex">
          <input class="form-control mr-sm-2" type="text" name="q" id="searchInput" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
  </nav>
    <!-- End of navigation bar-->
    
    
    
    <div class="container">

      <div class="row">
  
          <div class="col md-12">

            <p align="right">
  
        
           <a  class="btn btn-success  pull-left" href="{{ url_for('.insert' ) }}">Add Student</a>
                        
          </p>
          
  
    
    </form>

    <!-- Table -->
    <table class="table container">
        <thead>
          <tr>
            <th scope="col"></th>
            <th scope="col">ID no.</th>
            <th scope="col">Name</th>
            <th scope="col">Year</th>
            <th scope="col">Gender</th>
            <th scope="col">Course</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
            {% for student in students %}
            <tr>
                <th><img src="{{ cloudinary_url(student.6, format='jpg', width=32, height=32, crop='fill', gravity='center')[0] }}"></th>
                <th>{{student.0}}</th>
                <th>{{student.1}} {{student.2}} </th>
                <th>{{student.3}}</th>
                <th>{{student.4}}</th>
                <th>{{student.5}}</th>
                <th>
                  <a  class="btn btn-primary" href="{{ url_for('.update', id_number=student.0) }}">Update</a>
                    <a class="btn btn-danger" href="{{ url_for('.delete', id_number=student.0) }}">Delete</a>
                        

                </th>
            </tr>
            {% endfor %}
        </tbody>
      </table>
    <!-- End of Table-->



  </body>
</html>