app/views/courses/__init__.py
from flask import Blueprint

course = Blueprint('course', __name__)

from . import routes

app/views/courses/routes.py
from flask import Flask, render_template, request, redirect, url_for, flash
from ...models.courses import Courses
from . import course
from ... import db,mycursor

@course.route('/courses')
def courses():
    data = Courses().get_all()
    return render_template('/courses/index.html', courses=data )

@course.route('/delete/<string:code>', methods = ['GET'])
def delete(code):
    flash("Deleted Successfully")
    mycursor.execute("DELETE FROM courses WHERE code=%s", (code,))
    db.commit()
    return redirect(url_for('course.courses')) 


@course.route('/insert', methods = ['POST', 'GET'])
def insert():

    if request.method == "POST":
        flash("Data Saved Successfully")
        code = request.form['code']
        name = request.form['name']
        colleges = request.form['colleges']
      
        mycursor.execute("INSERT INTO courses (code, name, colleges ) VALUES (%s,%s, %s)", (code, name, colleges))
        db.commit()
        return redirect(url_for('course.courses'))
    return render_template('/courses/add.html')



@course.route('/update/<string:code>',methods=['POST','GET']) 
def update(code):

    if request.method == 'POST':
        newcode = request.form['code']
        name = request.form['name']
        colleges = request.form['colleges']
        mycursor.execute("""
               UPDATE courses
               SET code=%s, name=%s, colleges=%s
               WHERE code=%s
            """, (newcode, name, colleges, code))
        flash("Data Updated Successfully")
        db.commit()
        return redirect(url_for('course.courses'))
    data = Courses().get_one(code)
    return render_template('/edit/course2.html',code=code, data=data)


@course.route('/search')
def search():
    q = request.args.get('q') or None
    data = Courses().search(q)
    return render_template('/courses/index.html', courses=data )

app/templates/courses/add.html
{% extends "base.html" %}
{% block title %} Create Course{% endblock %}
{% block content %}
<h1> Simple Student Information System </h1>
<section class="create-type">
	<div class="container">
		<h2>CREATE COURSE HERE</h2>
		{% with messages = get_flashed_messages() %}
			{% if messages %}
				{% for msg in messages %}
					<p class="text-center">{{msg}}</p>
				{% endfor %}
			{% endif %}
		{% endwith %}
		<form action="" method="POST" class="form-group">
			<label for="code" class="form-label">course code</label>
			<input type="text" class="form-control" id="code" name="code" placeholder="e.g BSIT">

			<label for="name" class="form-label">course name</label>
			<input type="text" class="form-control" id="name" name="name" placeholder="e.g Bachelor of Science in Information Technology">

			<label for="colleges" class="form-label">college code</label>
			<input type="text" class="form-control" id="colleges" name="colleges" placeholder="e.g CCS">
			<input type="submit" name="submit-course" class="btn btn-primary form-control" value="Create">
			<a href="{{ url_for('course.courses' ) }}" class="btn btn-info form-control">Back</a>
		</form>
	</div>
</section>
{% endblock %}

app/templates/courses/index.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="../static/style.css">

    <title>SSIS</title>
  </head>



  <body>

    <!-- Navigation bar-->
    <nav class="navbar container">
      <div class="nav-item pull-left">
      <ul class="nav">
          
          <a class="navbar-brand" href="/">
            <img src="{{url_for('static',filename='logo.png')}}" width="30" height="30" class="d-inline-block align-top" alt="" loading="lazy">
          </a>
          
          <li class="nav-item p-2" style="font-size:20px">
              <a href="{{url_for('student.students')}}" style="color:#850f13"><strong><u>Student List</u></strong></a>
          </li>
          <li class="nav-item p-2" style="font-size:20px">
              <a href="{{url_for('course.courses')}}" style="color:#ff5733"><strong>Course List</strong></a>
          </li>
         
          
          <li class="nav-item p-2" style="font-size:20px">
              <a href="{{url_for('college.colleges')}}" style="color:#850f13"><strong>College List</strong></a>
          </li>
      </ul>
      </div>
      <form action="{{url_for('course.search')}}" method="GET" class="form-inline my-2 my-lg-0 d-flex">
          <input class="form-control mr-sm-2" type="text" name="q" id="searchInput" placeholder="Search" aria-label="Search" >
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button> 
      </form>
  </nav>
    <!-- End of navigation bar-->
    
    
    
    <div class="container">

      <div class="row">
  
          <div class="col md-12">

            <p align="right">
  
           <a class="btn btn-success  pull-left" href="{{ url_for('course.insert' ) }}">Add Course</a>
          </p>
          
          
  
    
    </form>

    <!-- Table -->
    <table class="table container">
        <thead>
          <tr>
            <th scope="col">Code</th>
            <th scope="col">Name</th>
            <th scope="col">Colleges</th>
            <th scope="col">Actions</th>
            
          </tr>
        </thead>
        <tbody>
            {% for course in courses %}
            <tr>
                <th>{{course.0}}</th>
                <th>{{course.1}}</th>
                <th>{{course.2}}</th>
               
                <th>
                  <a  class="btn btn-primary" href="{{ url_for('.update', code=course.0) }}">Update</a>
                  <a class="btn btn-danger" href="{{ url_for('.delete', code=course.0) }}">Delete</a>
                      
                </th>
            </tr>
            {% endfor %}
        </tbody>
      </table>
    <!-- End of Table-->



  </body>
</html>